#!/bin/sh

# Update revisions number
bash "scripts/update_version" > /dev/null

# add keys to file
bash "scripts/expose_clientID" > /dev/null

# Copy website files
sudo cp -r ./public/* /var/www/

# replace real keys with placeholders
bash "scripts/hide_clientID" > /dev/null

echo "Finished deploying version $(cat version)"


